### ISSUE TITLE
Error 401 on Get Sensor

### ISSUE THREAD

**Issue by mleglise** [IceBotYT/lacrosse_view#4]
### Request
Could we please get the `device_id` printed out as part of the "Failed to get sensor..." error message?
https://github.com/IceBotYT/lacrosse_view/blob/f5ad547dfb1c0a2d6b0a20c062ac4cc0752634a8/src/lacrosse_view/__init__.py#L232

### Problem Observed
Started by configuring [LaCrosse View integration](https://www.home-assistant.io/integrations/lacrosse_view) in Home Assistant. Input the username and password. Then it kept failing with error message: `Failed to get sensor, status code: 401`

Full error log from Home Assistant:
```
2022-12-18 17:49:23.416 ERROR (MainThread) [homeassistant.components.lacrosse_view] Unexpected error fetching LaCrosse View data: Failed to get sensor, status code: 401
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/lacrosse_view/coordinator.py", line 63, in _async_update_data
sensors = await self.api.get_sensors(
File "/usr/local/lib/python3.10/site-packages/lacrosse_view/__init__.py", line 242, in get_sensors
raise HTTPError(
lacrosse_view.HTTPError: Failed to get sensor, status code: 401
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/components/lacrosse_view/coordinator.py", line 70, in _async_update_data
raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: Failed to get sensor, status code: 401
```

### Troubleshooting
Tracing down through the code, it looks like this library gets all the way through retrieving the location data, then starts trying to iterate through the device list. (Meaning all the authentication and API calls worked so far.)
https://github.com/IceBotYT/lacrosse_view/blob/f5ad547dfb1c0a2d6b0a20c062ac4cc0752634a8/src/lacrosse_view/__init__.py#L182

But then inside that loop, it hits a non-200 response code and errors out completely.
https://github.com/IceBotYT/lacrosse_view/blob/f5ad547dfb1c0a2d6b0a20c062ac4cc0752634a8/src/lacrosse_view/__init__.py#L232

I know I have ~7 devices in my list, but other than scripting this out myself, there's no information at all about which device failed or succeeded. Could we please get the `device_id` printed out as part of the error message?

### Bonus
Perhaps this logic could be improved so that 1 device failing doesn't stop the rest from returning data?

**Comment by IceBotYT** [comment]
Thank you for this detailed issue. I will definitely work on this when I have the free time :)
Currently digging through HA issues first
